#!/bin/bash

# Sätt din lokala sites mapp
LOCALPATH="$HOME/Sites"

# Ange databasuppgifter för lokal MySQL
DBUSER="root"
DBPASS="root" # Ändra till ditt lösenord
DBHOST="localhost"

# Fråga användaren om input för variablerna
read -p "Ange site-URL (exempel.se): " SITEURL
read -p "Ange server-ID: " SERVER
read -p "Ange sitens server path relativt från www/: (Tryck bara Enter om siten ligger i www roten, annars ex: site.se/)" SITEPATH




# Skapa lokal mapp och navigera till den
mkdir -p "${LOCALPATH}/${SITEURL}" && cd "${LOCALPATH}/${SITEURL}"

# Skapa lokal databas (konvertera punkter till understreck för DB-namn)
DBNAME=$(echo "${SITEURL}" | tr '.' '_')

# Skapa databasen lokalt
echo "Skapar lokal databas '${DBNAME}'..."
mysql -u"${DBUSER}" -p"${DBPASS}" -h"${DBHOST}" -e "CREATE DATABASE IF NOT EXISTS ${DBNAME} DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>/dev/null

# Synka filer från servern
echo "Synkar filer från: ${SERVER}@srv01:public_html/${SITEPATH}"
rsync -a "${SERVER}@srv01:public_html/${SITEPATH}" ./ --exclude={'.well-known','.wp-cli','cgi-bin'}

# Uppdatera wp-config.php med lokala DB-uppgifter
if [ -f wp-config.php ]; then
    sed -i.bak "s/define( *'DB_NAME'.*/define( 'DB_NAME', '${DBNAME}' );/" wp-config.php
    sed -i "" "s/define( *'DB_USER'.*/define( 'DB_USER', '${DBUSER}' );/" wp-config.php
    sed -i "" "s/define( *'DB_PASSWORD'.*/define( 'DB_PASSWORD', '${DBPASS}' );/" wp-config.php
else
    echo "wp-config.php saknas. Uppdatera manuellt."
fi

# Ta bort object-cache.php lokalt
rm -f ./wp-content/object-cache.php

# Exportera databas på servern och ladda ner den
echo "Synkar ner databas.."
ssh "${SERVER}@srv01" "cd www/${SITEPATH} && wp db export db.sql"
scp "${SERVER}@srv01:www/${SITEPATH}/db.sql" ./
ssh "${SERVER}@srv01" "cd www/${SITEPATH} && rm db.sql"

# Importera databasen lokalt
wp db import db.sql 2>/dev/null

# Ersätt URL i databasen

# Hämta nuvarande siteurl från databasen
OLD_SITEURL=$(wp option get siteurl)

# Ny siteurl för lokal miljö
NEW_SITEURL="http://${SITEURL}.test"

echo "Ersätter ${OLD_SITEURL} med ${NEW_SITEURL} i databasen..."
wp search-replace "${OLD_SITEURL}" "${NEW_SITEURL}" --skip-columns=guid --quiet

# Cleanup
wp rewrite flush
wp cache flush
wp elementor flush-css --regenerate
rm db.sql


echo "Färdigt -> ${NEW_SITEURL}"
