#!/bin/bash

# Sätt din lokala sites mapp
LOCALPATH="$HOME/Sites"

# Ange databasuppgifter för lokal MySQL
DBUSER="haus"
DBPASS="life" # Ändra till ditt lösenord
DBHOST="localhost"

# Fråga användaren om input för variablerna
read -p "Ange site-URL (exempel.se): " SITEURL
read -p "Ange server-ID: " SERVER
read -p "Ange sitens server path relativt från www/: (Tryck bara Enter om siten ligger i www roten, annars ex: site.se/)" SITEPATH


# Säkerställ att SITEPATH slutar med slash (om den inte är tom)
if [[ -n "$SITEPATH" && "${SITEPATH: -1}" != "/" ]]; then
    SITEPATH="${SITEPATH}/"
fi


# Navigera till befintlig mapp
cd "${LOCALPATH}/${SITEURL}"


# Synka wp-content från servern
echo "Synkar filer från: ${SERVER}@srv01:public_html/${SITEPATH}"
rsync -a "${SERVER}@srv01:public_html/${SITEPATH}" ./ \
  --include='wp-content/' \
  --include='wp-content/***' \
  --exclude='wp-content/plugins/site-widgets/' \
  --exclude='wp-content/plugins/webien-site-widgets/' \
  --exclude='*'



# Exportera databas på servern och ladda ner den
echo "Synkar ner databas.."
ssh "${SERVER}@srv01" "cd www/${SITEPATH} && wp db export db.sql"
scp "${SERVER}@srv01:www/${SITEPATH}/db.sql" ./
ssh "${SERVER}@srv01" "cd www/${SITEPATH} && rm db.sql"

# Importera databasen lokalt
wp db import db.sql 2>/dev/null

# Ersätt URL i databasen

# Hämta nuvarande siteurl från databasen
OLD_SITEURL=$(wp option get siteurl)

# Ny siteurl för lokal miljö
NEW_SITEURL="http://${SITEURL}.test"

echo "Ersätter ${OLD_SITEURL} med ${NEW_SITEURL} i databasen..."
wp search-replace "${OLD_SITEURL}" "${NEW_SITEURL}" --skip-columns=guid --quiet

# Cleanup
wp rewrite flush
wp cache flush
wp elementor flush-css --regenerate
rm db.sql

wp plugin deactivate litespeed-cache


echo "Färdigt -> ${NEW_SITEURL}"
